# Generated by Django 2.0.2 on 2020-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200127_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='issues',
            field=models.CharField(default='No Issues', max_length=50),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='issues',
            field=models.CharField(default='No Issues', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='issues',
            field=models.CharField(default='No Issues', max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
